### ISSUE TITLE
Bug: submissions showing up for wrong question in submissions page

### ISSUE THREAD

**Issue by vivienherq** [tryyang2001/CS3213-Frontend-Management-System#108]
This student should have 3 submissions for Assignment 1 question 1 and none for question 2, but the submissions are showing up for the wrong question.

<img width="1508" alt="Screenshot 2024-04-17 at 4 32 50 PM" src="https://github.com/tryyang2001/CS3213-Frontend-Management-System/assets/100022021/b192733e-9871-4fac-8a5f-0ced38eb903a">

**Comment by tryyang2001** [comment]
Are the 3 submissions all for question 2 in the assignment? For the "no submission", is it because that student never submits any attempt for question 1?Also to view the 3 submissions, if you enter the submission detail page for question 2, on the top right corner, is the "Select" working?

**Comment by vivienherq** [comment]
> Are the 3 submissions all for question 2 in the assignment? For the "no submission", is it because that student never submits any attempt for question 1?Also to view the 3 submissions, if you enter the submission detail page for question 2, on the top right corner, is the "Select" working?

hmm, actually i believe it's all for question 1... but select is working... i'll modify the bug description
