### ISSUE TITLE
Standardize ways of creating PR

### ISSUE THREAD

**Issue by tryyang2001** [tryyang2001/CS3213-Frontend-Management-System#22]
Typically, a PR can be created by 2 ways:
1. Fork workflow: first fork the original repo, and then push changes to the forked repo and create PR to merge from forked to original.
2. Side-branch workflow: create side branch from an issue or manually, make any changes to the branch, and create PR to merge from side branch to master branch.

I want to decide and standardize the way we create PR, so we have to determine whether we want to use fork workflow or side-branch workflow.

Fyi, @WillCWX @hhchinh2002 @junhonglow @vivienherq

**Comment by tryyang2001** [comment]
Personally I prefer the **side-branch workflow**. Reason is because I am not very familiar with fork workflow, and I don't want to maintain 2 repo instead of 1. Furthermore, I am not familiar with reviewing a PR created from a forked repo as I can't simply pull the changes to local. I need to go to the forked repo, copy the repo link, and then clone to a new folder to review the changes... (Maybe I am dumb, is there a better & faster way to pull the changes locally?)

**Comment by WillCWX** [comment]
For the forked PRs, you can fetch and access them as a branch using
`git fetch origin pull/15/head:user-page-pr`
`git checkout user-page-pr`

The format is essentially 
`git fetch <remote_name> pull/<pr_number>/head:<your_name_for_this_branch>`
`git checkout <your_name_for_this_branch>`
(if you leave the branch name empty, the pr_number will be used as the name by default)

If your `origin` is a forked repo, you can add this repo as `upstream` or `<any_remote_name>` by doing 
`git add <remote_name> https://example.git`

**Comment by tryyang2001** [comment]
I see! However, I was using Sourcetree (GUI) for accessing git... (Sryy haha), so I wasn't able to run commands in terminal xD Anyway thank you so much for the info!

Then I think the issue with forked workflow is that I always need to maintain more than many repos, (upstream, my forked repo, and others' forked repo) just for a single project. And each forked repo seems to have different branches as well, so it might confuse me when reviewing :(

Any way can you vote the workflow that you prefer? Thanks!

**Comment by WillCWX** [comment]
Ah,
I personally prefer the forked workflow for a cleaner main repo (less stale branches and less accidental changes to master).
You don't really need to maintain other's forked repo since you only need to look at the pull requests (and fetch as a branch from there using the CLI).

But I think for our team, using the side-branch workflow maybe better for us to track our progress (individually and as a team) especially if most of us are using Sourcetree (which is lacking this CLI function for some reason :C)

**Comment by junhonglow** [comment]
I prefer branching as opposed to forking as well, partly because it is more convenient and it is clearer on what features are being worked on atm. 

Are we planning to delete branches once they have been merged?

**Comment by tryyang2001** [comment]
> Are we planning to delete branches once they have been merged?

Yes, I do plan to set auto-deletion of the branch once merged to master for clarity.

**Comment by hhchinh2002** [comment]
I'm fine with any of type.

**Comment by tryyang2001** [comment]
Ah, since our team doesn't really have a more preferred workflow, I will say that we just do whatever we are familiar with, either side branching or forking is fine. I don't think we need to strictly follow any SWE principles and best practices haha.
